# Generated by Django 6.0.8 on 2026-08-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0025_generationjob_is_archived_generationjob_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='use_turbo',
            field=models.BooleanField(default=False, help_text='Whether this job used the Turbo LoRA + sigma-shift speedup (see extras.md#turbo) -- resolved from the request + settings.TURBO_LEVEL at queue time (generation/api.py::_resolve_use_turbo), not editable after. Unlike use_spectrum, this also forces the `steps` field above to settings.TURBO_STEPS_T2V_I2V/TURBO_STEPS_R2V instead of preset.steps -- turbo is only useful at (or near) the step count its LoRA was trained for. Does NOT adjust estimated_seconds above -- same reasoning as use_spectrum.'),
        ),
    ]
