# Generated by Django 6.0.8 on 2026-08-30 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0026_generationjob_use_turbo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='generationjob',
            name='folders',
            field=models.ManyToManyField(blank=True, help_text='User-organizational tags (see JobFolder) -- purely a display/filter aid, no effect on rendering. A job may belong to any number of folders at once.', related_name='jobs', to='generation.jobfolder'),
        ),
        migrations.AddConstraint(
            model_name='jobfolder',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_folder_name'),
        ),
    ]
