# Generated by Django 6.0.8 on 2026-08-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0008_backfill_job_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='continues_audio',
            field=models.BooleanField(default=False, help_text="Feeds a short clipped tail of the immediately-preceding Clip's own rendered audio in as an ordinary reference-audio upload (see director/services.py's _predecessor_audio_tail_bytes()/_build_job_for_clip()) -- deliberately NOT the Contex-Loop extension's own chain-state audio carryover, which pins the previous scene's tail as this scene's 'sound so far' and came back as continuous gibberish on a real render (see motion_context.py). Only meaningful alongside continues_previous and mode=r2v (only r2v has reference-audio slots to feed it into) -- enforced in the API layer, silently dropped rather than failing a render if either stops holding (e.g. continues_previous was just turned off). Experimental: unlike video motion continuity, this hasn't been verified against a real render yet."),
        ),
        migrations.AlterField(
            model_name='clip',
            name='continues_previous',
            field=models.BooleanField(default=False, help_text="Splice motion continuity from the immediately-preceding Clip's render (real chain continuity when available, a last-frame fallback otherwise -- see integrations/motion_context.py). Only meaningful when mode is in CONTINUATION_CAPABLE_MODES and this isn't the project's first Clip -- enforced in the API layer, not here. Governs positional/structural continuation (ordering, duration/resolution locking, chain walking) independently of continues_audio below -- audio carryover stopped riding on this flag after a real render came back as unbroken gibberish (see motion_context.py's audio_mode docstring for the story)."),
        ),
    ]
