# Generated by Django 6.0.8 on 2026-08-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0009_clip_continues_audio_alter_clip_continues_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_turbo',
            field=models.BooleanField(default=False, help_text="Whether every Clip in this project renders with the Turbo LoRA speedup (see extras.md#turbo) -- same project-wide reasoning as quality_label above, since turbo forces a fixed low step count that overrides quality_label's own steps entirely. Still gated server-side by settings.TURBO_LEVEL at render time (see generation/api.py::_resolve_use_turbo, called from director/services.py's _build_job_for_clip()) -- this field alone doesn't guarantee turbo actually applies, e.g. it's ignored if TURBO_LEVEL is None (not offered) and forced True regardless if TURBO_LEVEL is 2. Changing it marks every clip dirty but does NOT recompute width/height (unlike aspect_ratio/quality_label) -- turbo doesn't change resolution."),
        ),
    ]
